server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: developer123#
    url: jdbc:postgresql://localhost:5432/zip_metrics
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgresSQLDialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher